server:
  port: ${datasource.dev-server-port}

spring:
  datasource:
    driver-class-name: ${datasource.dev-driver-class-name}
    url: ${datasource.dev-url}
    username: ${datasource.dev-username}
    password: ${datasource.dev-password}

  h2:
    console:
      enabled: true
      path: ${datasource.dev-h2-console-url}